---
- name: testing looping statements
  become: no
  hosts: all
  tasks: 
   - name: creating two files
     ansible.builtin.file:
       path: "{{ item }}"
       state: touch
     loop:
     - /tmp/1.txt
     - /tmp/2.txt
  
  
  
  
  
  
  
  